config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
      sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
  }

  scope module: :public do
    root to:"homes#top"
    get 'home/about'=>"homes#about", as: "about"
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    get 'customers/withdraw'=>'customers#withdraw'
    resources :items,only:[:index,:show]
    resource :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
      end
    end
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
  end


   namespace :admin do
     root to:"homes#top"
     resources :items
     resources :genres,only:[:index,:create,:edit,:update]
     resources :customers,only:[:index,:show,:edit,:update]
     resources :orders,only:[:show,:update]
     resources :orders_details,only:[:update]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    (item.price * 1.1).floor * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  def tax_price
    (price * 1.1).floor
  end  

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {awaiting_payment:0,payment_confirmation:1,under_manufacture:2,preparing_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { can_not_start:0,awaiting_production:1,under_manufacture:2,manufacturing_completed:3}
  def subtotal
    (price*1.1).floor * amount
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def create
    @item=Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details__helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessionss_helper.rb
module SessionssHelper
end

app/views/admin/items/edit.html.erb
<div class="w-25 mx-auto">
  <h4>商品編集</h4>
  <%= form_with model: @item,url:admin_item_path(@item) do |f| %>
    <h6>商品画像</h6>
    <%= f.file_field :image, accept: "image/*" %>

    <h6>商品名</h6>
    <%= f.text_field :name %>

    <h6>商品説明</h6>
    <%= f.text_area :introduction %>

	  <h6>ジャンル</h6>
	  <%= f.collection_select :genre_id, Genre.all, :id, :name %>

	  <h6>税抜価格</h6>
	  <%= f.text_field :price %>円

	  <h6>販売ステータス</h6>
	  <%= f.radio_button :is_active,true %>
    <%= f.label :is_active, "販売中" %>

    <%= f.radio_button :is_active,false %>
    <%= f.label :is_active, "販売停止中" %>

    <h6 class="m-5"><%= f.submit '変更を保存' %></h6>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="w-25 mx-auto">
  <h2>商品一覧</h2>
    <div class="text-right">
      <%= link_to "＋", new_admin_item_path,class: "text-white btn btn-bg-dark rounded-circle bg-dark" %>
    </div>
  <table class="table">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%=link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.name %></td>
          <td>
            <% if item.is_active %>
            販売中
            <% else %>
            販売停止中
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="w-25 mx-auto">
  <h2>商品新規登録</h2>
  <%= form_with model: @item,url:admin_items_path, method: :post do |f| %>
    <h4>商品画像</h4>
    <%= f.file_field :image, accept: "image/*" %>

    <h4>商品名</h4>
    <%= f.text_field :name %>

    <h4>商品説明</h4>
    <%= f.text_area :introduction %>

	  <h4>ジャンル</h4>
	  <%= f.collection_select :genre_id, Genre.all, :id, :name %>

	  <h4>税抜価格</h4>
	  <%= f.text_field :price %>

	  <h4>販売ステータス</h4>
	  <%= f.radio_button :is_active,true %>
    <%= f.label :is_active, "販売中" %>

    <%= f.radio_button :is_active,false %>
    <%= f.label :is_active, "販売停止中" %>

    <h4 class="m-5"><%= f.submit '新規登録' %></h4>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="w-25 mx-auto">
  <h2>商品詳細</h2>
  <div>
    <%= image_tag @item.get_image(100,100) %>
    <p>商品名：<%= @item.name %></p>
    <p>商品説明：<%= @item.introduction %></p>
    <p>ジャンル：<%= @item.genre_id %></p>
    <p>税込価格(税抜価格)：<%= @item.price %>円</p>
    <p>販売ステータス：
    <% if @item.is_active? %>
    　販売中
    <% else %>
      販売停止中
    <% end %>
    </p>
    <%= link_to "編集する", edit_admin_item_path(@item.id) %>
  </div>
</div>