config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
      sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
  }

  scope module: :public do
    root to:"homes#top"
    get 'home/about'=>"homes#about", as: "about"
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    get 'customers/withdraw'=>'customers#withdraw'
    resources :items,only:[:index,:show]
    resource :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
      end
    end
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
  end


   namespace :admin do
     root to:"homes#top"
     resources :items
     resources :genres,only:[:index,:create,:edit,:update]
     resources :customers,only:[:index,:show,:edit,:update]
     resources :orders,only:[:show,:update]
     resources :orders_details,only:[:update]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    (item.price * 1.1).floor * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  def tax_price
    (price * 1.1).floor
  end  

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {awaiting_payment:0,payment_confirmation:1,under_manufacture:2,preparing_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { can_not_start:0,awaiting_production:1,under_manufacture:2,manufacturing_completed:3}
  def subtotal
    (price*1.1).floor * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.page(params[:page])
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer)
  end

     private
  def customer_params
    params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details__helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessionss_helper.rb
module SessionssHelper
end

app/views/admin/customers/edit.html.erb
<div class="w-25 mx-auto">
  <h4>
    <%= @customer.first_name %>
    <%= @customer.last_name %>
    の会員情報編集
  </h4>
  <%= form_with model: @customer,url:admin_customer_path, method: :patch do |f| %>
    <h6>会員ID</h6>
    <%= @customer.id %>

    <h6>氏名</h6>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>

    <h6>フリガナ</h6>
    <%= f.text_field :first_name_kana %>
    <%= f.text_field :last_name_kana %>

    <h6>郵便番号</h6>
    <%= f.text_field :postal_code %>

    <h6>住所</h6>
    <%= f.text_field :address %>

    <h6>電話番号</h6>
    <%= f.text_field :telephone_number %>

    <h6>メールアドレス</h6>
    <%= f.text_field :email %>

    <h6>会員ステータス</h6>
    <%= f.radio_button :is_deleted,true %>
    <%= f.label :is_deleted, "退会" %>

    <%= f.radio_button :is_deleted,false %>
    <%= f.label :is_deleted, "有効" %>

    <h6 class="m-5"><%= f.submit '変更を保存' %></h6>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="w-25 mx-auto">
  <h8>会員一覧</h8>
  <table class="table tabli-hover table-inverse">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.first_name %>
            <%= customer.last_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_deleted %>
          退会
          <% else %>
         有効
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="w-25 mx-auto">
  <h4>
    <%= @customer.first_name %>
    <%= @customer.last_name %>
    の会員詳細
  </h4>
  <table class="table tabli-hover table-inverse">
    <tbody>
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td>
          <%= @customer.first_name %>
          <%= @customer.last_name %>
        </td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td>
          <%= @customer.first_name_kana %>
          <%= @customer.last_name_kana %>
        </td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td>
          <% if @customer.is_deleted %>
           退会
          <% else %>
          有効
          <% end %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to '編集する',edit_admin_customer_path(@customer) %></td>
        <td><%= link_to '注文履歴一覧を見る',admin_root_path(@customer) %></td>
      </tr>
    </tbody>
  </table>
</div>