config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
      sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
  }

  scope module: :public do
    root to:"homes#top"
    get 'home/about'=>"homes#about", as: "about"
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    get 'customers/withdraw'=>'customers#withdraw'
    resources :items,only:[:index,:show]
    resource :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
      end
    end
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
  end


   namespace :admin do
     root to:"homes#top"
     resources :items
     resources :genres,only:[:index,:create,:edit,:update]
     resources :customers,only:[:index,:show,:edit,:update]
     resources :orders,only:[:show,:update]
     resources :orders_details,only:[:update]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    (item.price * 1.1).floor * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  def tax_price
    (price * 1.1).floor
  end  

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {awaiting_payment:0,payment_confirmation:1,under_manufacture:2,preparing_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { can_not_start:0,awaiting_production:1,under_manufacture:2,manufacturing_completed:3}
  def subtotal
    (price*1.1).floor * amount
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details=@order.order_details
    if params[:order][:status]=="payment_confirmation"
      @order_details.update_all(making_status: "awaiting_production")
    end
    @order.update(status: params[:order][:status])
    redirect_to admin_order_path(@order.id)
  end

  private
  def order_params
        params.require(:order).permit(:status)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details__helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessionss_helper.rb
module SessionssHelper
end

app/views/admin/orders/show.html.erb
<div class="w-50 mx-auto">
  <h4>注文履歴詳細</h4>
    <div>
      <div>
        氏名: <%= @order.shipping_name %>
      </div>
      <div>
        注文日: <%= @order.created_at %>
      </div>
      <div>
        配送先: <%='〒' +  @order.shipping_postal_code + ' ' +  @order.shipping_address + ' ' +  @order.shipping_name %>
      </div>
      <div>
        支払方法: <%= @order.payment_method_i18n %>
      </div>
      <div>
        <%= form_with model: @order,url: admin_order_path(@order.id),method: :patch  do |f| %>
          <%= f.label :注文ステータス %>
          <%= f.select :status, Order.statuses_i18n.invert %>
          <%= f.submit '更新' %>
        <% end %>
      </div>
    </div>
  <table class="table tabli-hover table-inverse">
    <thead class="thead-light">
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @order_details.each do |detail| %>
      <tr>
        <td><%= detail.item.name %></td>
        <td><%= (detail.price*1.1).floor %></td>
        <td><%= detail.amount %></td>
        <td><%= detail.subtotal %></td>
        <td>
          <%= form_with model: detail,url: admin_orders_detail_path(detail.id),method: :patch  do |f| %>
            <%= f.label :製作ステータス %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
            <%= f.submit '更新' %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <table class="table tabli-hover table-inverse">
    <tr>
      <th>商品合計</th>
      <td><%= @order.total_payment - @order.shipping_cost %></td>
    </tr>
    <tr>
      <th>送料</th>
      <td><%= @order.shipping_cost %></td>
    </tr>
    <tr>
      <th>請求金額合計</th>
      <td><%= @order.total_payment %></td>
    </tr>
  </table>
</div>

app/views/orders/complete.html.erb
<div>
  <p class="text-md-center">ご注文ありがとうございました！</p>
</div>