config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
      sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
  }

  scope module: :public do
    root to:"homes#top"
    get 'home/about'=>"homes#about", as: "about"
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    get 'customers/withdraw'=>'customers#withdraw'
    resources :items,only:[:index,:show]
    resource :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :orders,only:[:new,:create,:index,:show] do
      collection do
        post 'confirm'
      end
    end
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
  end


   namespace :admin do
     root to:"homes#top"
     resources :items
     resources :genres,only:[:index,:create,:edit,:update]
     resources :customers,only:[:index,:show,:edit,:update]
     resources :orders,only:[:show,:update]
     resources :orders_details,only:[:update]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    (item.price * 1.1).floor * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  def tax_price
    (price * 1.1).floor
  end  

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {awaiting_payment:0,payment_confirmation:1,under_manufacture:2,preparing_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { can_not_start:0,awaiting_production:1,under_manufacture:2,manufacturing_completed:3}
  def subtotal
    (price*1.1).floor * amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details__helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessionss_helper.rb
module SessionssHelper
end

app/views/admin/items_controller.html.erb
<h1>Admin#items_controller</h1>
<p>Find me in app/views/admin/items_controller.html.erb</p>

app/views/admin/sessionss_controller.html.erb
<h1>Admin#sessionss_controller</h1>
<p>Find me in app/views/admin/sessionss_controller.html.erb</p>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to root_path do %>
          <div class="navbar-brand" href="#">LOGO</div>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to customers_path do %>
                <div class="nav-link">マイページ</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to items_path do %>
                <div class="nav-link">商品一覧</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to cart_items_path do %>
                <div class="nav-link">カート</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  destroy_customer_session_path, method: :delete do %>
                <div class="nav-link">ログアウト</div>
              <% end %>
            </li>

          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_items_path do %>
                <div class="nav-link">商品一覧</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_customers_path do %>
                <div class="nav-link">会員一覧</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_root_path do %>
                <div class="nav-link">注文履歴一覧</div>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to admin_genres_path do %>
                <div class="nav-link">ジャンル一覧</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  destroy_admin_session_path, method: :delete do %>
                <div class="nav-link">ログアウト</div>
              <% end %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to about_path do %>
                <div class="nav-link">About</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to items_path do %>
                <div class="nav-link">商品一覧</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_customer_registration_path do %>
                <div class="nav-link">新規登録</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_customer_session_path do %>
                <div class="nav-link">ログイン</div>
              <% end %>
            </li>
          <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="footer"></footer>
  </body>
</html>